[book]
authors = ["ddorgan"]
language = "en"
multilingual = false
src = "src"
title = "Substrate Devops Guide"

[output.html]
additional-css = ["last-changed.css"]
default-theme = "Ayu"
git-repository-url = "https://github.com/paritytech/devops-guide"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/paritytech/devops-guide/edit/master/{path}"
site-url = "/devops-guide/"

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]
